// Shared default blog articles — separated from Blog.tsx page to allow clean Fast Refresh

export const defaultConstructionArticles = [
  {
    id: "b1",
    slug: "saptakoshi-river-bridge-deep-well-pier-milestone",
    title: "Saptakoshi River Bridge: Deep-Well Foundation Pier Milestone Completed Ahead of Monsoon",
    category: "Project Milestones",
    excerpt: "Our heavy bridge engineering division successfully completed all deep-well pier caissons for the Saptakoshi River crossing, beating the critical monsoon flood window by three weeks.",
    content: "Constructing multi-span bridges across Nepal's major perennially flooded rivers requires immaculate seasonal timing and deep hydraulic engineering expertise.\n\nOn the Saptakoshi River Bridge contract (Province 1 · ₨ 2.4B), MK Construction deployed pneumatic well-sinking rigs and bentonite-stabilized excavation techniques to anchor 18 bridge piers into bedrock beneath 22 meters of shifting alluvial silt. Working in round-the-clock winter shifts, our crew placed over 14,000 cubic meters of high-density M35 structural concrete.\n\nAll deep pier caps are now secured above the maximum anticipated 100-year flood line, allowing superstructure pre-stressed girder launching to proceed smoothly without risk of seasonal inundation.",
    thumbnail_url: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&q=80&w=1200",
    author: "Er. Rameshwor Adhikari",
    published_at: "2026-09-18",
    read_time: "5 min read",
    views: 1420,
    is_featured: true,
  },
  {
    id: "b2",
    slug: "mk-construction-awarded-mid-hill-highway-pkg-7",
    title: "MK Construction Awarded Mid-Hill Highway Package 7 Asphalt Paving Contract (₨ 1.9B)",
    category: "Tender Wins",
    excerpt: "The Department of Roads has officially awarded MK Construction Company Pvt. Ltd. the turnkey 48-kilometer double-lane asphalt concrete and slope stabilization contract in Karnali Province.",
    content: "The Ministry of Physical Infrastructure and Transport, Department of Roads (DoR), has formally executed the contract agreement with MK Construction Company Pvt. Ltd. for Mid-Hill Highway Package 7 in Karnali Province.\n\nThe ₨ 1.9B works package encompasses widening the existing alignment to double-lane standards, deep rock cutting in steep mountainous terrain, bio-engineering slope stabilization, reinforced concrete box culverts, and 48 kilometers of asphalt concrete surfacing.\n\nMobilization of our captive CAT excavators, motor graders, and mobile aggregate crushing plants is underway at the site depot.",
    thumbnail_url: "https://images.unsplash.com/photo-1541976590-713941681591?auto=format&fit=crop&q=80&w=1200",
    author: "Sunita Pradhan",
    published_at: "2026-09-08",
    read_time: "4 min read",
    views: 980,
    is_featured: false,
  },
  {
    id: "b3",
    slug: "bagmati-river-training-12km-embankment-completion",
    title: "Bagmati River Training: 12-Kilometer Flood Mitigation Embankment & Spur Defense Commissioned",
    category: "Project Milestones",
    excerpt: "Deploying high-density gabion mattresses and reinforced concrete spurs, our hydraulic teams successfully fortified 12 kilometers of vulnerable river basin to safeguard surrounding settlements.",
    content: "Monsoon floods regularly devastate agricultural riverbanks and urban settlements across the Terai and inner valleys. On the Bagmati River Training project (₨ 1.2B), MK Construction engineered an integrated flood defense system designed to withstand high hydraulic discharge.\n\nThe project incorporates 12 kilometers of earthen embankment armored with geotextile filter layers, wire-mesh gabion revetments, and RCC deflective spurs that redirect river flow away from vulnerable banks.\n\nIndependent quality testing by the Department of Water Resources confirmed zero scour degradation after initial high-flow stress trials.",
    thumbnail_url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=1200",
    author: "Er. Rameshwor Adhikari",
    published_at: "2026-08-25",
    read_time: "6 min read",
    views: 1150,
    is_featured: false,
  },
  {
    id: "b4",
    slug: "seismic-resilient-building-nbc-105-2020",
    title: "Implementing NBC 105:2020: Advanced Ductile Detailing for Seismic-Resistant Institutional Buildings",
    category: "Sector Commentary",
    excerpt: "An engineering breakdown of how MK Construction translates Nepal Building Code (NBC 105:2020) seismic requirements into high-ductility shear walls and beam-column junction reinforcement.",
    content: "Nepal is situated in an active seismic subduction zone, making seismic engineering compliance not merely a legal mandate, but a critical life-safety imperative.\n\nUnder Nepal Building Code (NBC 105:2020), seismic coefficients and ductile detailing standards have been substantially heightened. On the Lumbini Provincial HQ Complex (₨ 980M), MK Construction integrated advanced response spectrum analysis into structural modeling, utilizing Fe500D thermo-mechanically treated rebar and closely spaced confinement ties at critical beam-column nodes.\n\nOur on-site QA/QC laboratory verifies 100% of rebar tensile elongation and concrete cube compressive strengths prior to formwork striking.",
    thumbnail_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200",
    author: "Er. Binod K. Thapa, M.Sc.",
    published_at: "2026-08-12",
    read_time: "7 min read",
    views: 890,
    is_featured: false,
  },
  {
    id: "b5",
    slug: "fleet-expansion-mobile-batching-crushers",
    title: "MK Construction Expands Captive Heavy Fleet with 3 Mobile Batching Plants and 12-Ton Tandem Rollers",
    category: "Company Announcements",
    excerpt: "Strengthening our self-performance capabilities across western Nepal, MK Construction has inducted new mobile computerized wet-mix batching plants and GPS-telemetry compaction rollers.",
    content: "To guarantee schedule certainty and eliminate dependency on third-party suppliers in remote project zones, MK Construction Company Pvt. Ltd. has completed a major fleet expansion of our heavy civil engineering machinery.\n\nThe new additions include three mobile computerized concrete batching plants capable of 120 m³/hr output, four Hamm 12-ton tandem vibratory rollers with continuous density sensors, and six multi-axle tippers.\n\nThis fleet expansion boosts our active equipment inventory to over 500 operational units across 32 districts.",
    thumbnail_url: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&q=80&w=1200",
    author: "Er. M.K. Shrestha, PE",
    published_at: "2026-07-29",
    read_time: "4 min read",
    views: 740,
    is_featured: false,
  },
  {
    id: "b6",
    slug: "run-of-river-hydropower-civil-works-challenges",
    title: "Civil Engineering in Steep Himalayan Topography: Excavating Tunnels & Surge Tanks for Hydropower",
    category: "Sector Commentary",
    excerpt: "Insights into rock mass classification (RMR/Q-system), NATM tunneling support, and torrential water diversion strategies executed across high-gradient Nepali river valleys.",
    content: "Developing run-of-river hydropower civil infrastructure in the Himalayas demands mastery over fragile geology, high hydraulic heads, and flash-flood risks.\n\nOn the Upper Trishuli Run-of-River civil package (₨ 3.1B), MK Construction's tunneling teams executed drill-and-blast excavation supported by fiber-reinforced shotcrete, lattice girders, and self-drilling rock anchors.\n\nBy continuously monitoring rock convergence with optical 3D targets, our engineers adjusted primary support classes dynamically, achieving zero collapse incidents across 3.4 kilometers of headrace tunnel.",
    thumbnail_url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=1200",
    author: "Er. Binod K. Thapa, M.Sc.",
    published_at: "2026-07-15",
    read_time: "8 min read",
    views: 810,
    is_featured: false,
  },
];
